In [1]:
import pandas as pd
from datetime import date
import calendar
from utils import snowflake_login, carga_snow_generic, descargar_segmento, get_credentials
import gspread
from gspread_dataframe import get_as_dataframe
from google.oauth2.service_account import Credentials
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import re
import streamlit as st
import numpy as np

In [2]:
#Funciones de redondeo
def red (r:float):
    allowed_numbers = [0.2, 0.25, 0.4, 0.5, 0.6, 0.75, 0.8, 1.0, 1.2, 1.25, 1.4, 1.5, 1.6, 1.75, 1.8, 2.0,
                       2.2, 2.25, 2.4, 2.5, 2.6, 2.75, 2.8, 3.0, 3.2, 3.25, 3.4, 3.5, 3.6, 3.75, 3.8, 4.0]
    closest_number = min(allowed_numbers, key=lambda x: abs(x - r))
    return closest_number

def red3 (r:float):
    allowed_numbers = [1.0, 2.0, 3.0, 4.0]
    closest_number = min(allowed_numbers, key=lambda x: abs(x - r))
    return closest_number

def red7 (r:float):
    allowed_numbers = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
    closest_number = min(allowed_numbers, key=lambda x: abs(x - r))
    return closest_number

#Funcion para cerrar la participación
def cerrar (df:pd.DataFrame):
    if df['PARTICIPACION'].sum() > 5.1:
        if df.shape[0] <= 3:
            df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                 ascending=False).head(1)['ITEM'].values[0]].index,
                   'PARTICIPACION'] = df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                                           ascending=False).head(1)['ITEM'].values[0]].index,
                                             'PARTICIPACION'] - 1
            df = cerrar(df)
            return df
        elif df.shape[0] <= 7:
            df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                 ascending=False).head(1)['ITEM'].values[0]].index,
                   'PARTICIPACION'] = df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                                           ascending=False).head(1)['ITEM'].values[0]].index,
                                             'PARTICIPACION'] - 0.5
            df = cerrar(df)
            return df
        else:
            df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                 ascending=False).head(1)['ITEM'].values[0]].index,
                   'PARTICIPACION'] = df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                                           ascending=False).head(1)['ITEM'].values[0]].index,
                                             'PARTICIPACION'] - 0.2
            df = cerrar(df)
            return df
    elif df['PARTICIPACION'].sum() < 4.9:
        if df.shape[0] <= 3:
            df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                 ascending=False).head(1)['ITEM'].values[0]].index,
                   'PARTICIPACION'] = df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                                           ascending=False).head(1)['ITEM'].values[0]].index,
                                             'PARTICIPACION'] + 1
            df = cerrar(df)
            return df
        elif df.shape[0] <= 7:
            df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                 ascending=False).head(1)['ITEM'].values[0]].index,
                   'PARTICIPACION'] = df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                                           ascending=False).head(1)['ITEM'].values[0]].index,
                                             'PARTICIPACION'] + 0.5
            df = cerrar(df)
            return df
        else:
            df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                 ascending=False).head(1)['ITEM'].values[0]].index,
                   'PARTICIPACION'] = df.loc[df[df['ITEM']==df.sort_values('PARTICIPACION',
                                                                           ascending=False).head(1)['ITEM'].values[0]].index,
                                             'PARTICIPACION'] + 0.2
            df = cerrar(df)
            return df
    else:
        return df

#Función para obtener la participación
def participacion (cursor, punt:pd.DataFrame, fecha_inicio:str):
    #Descargamos df
    dim = descargar_segmento(cursor=cursor, query='Dimensiones',
                             cond=f" and ip.fecha_inicio = '{fecha_inicio}';")
    ac = descargar_segmento(cursor=cursor, query='Aceleraciones').astype('str').replace('nan', pd.NA)

    #Cambiamos formato de columnas
    dim = dim.astype({'ITEM':'str', 'LOCAL':'str', 'ITEMS_POR_FRENTE':'int64',
                      'ITEMS_POR_LATERAL':'int64', 'CANT_MAX_X_ESTANTE':'int64', 'CANT_MIN_X_ESTANTE':'int64'})
    ac = ac.astype({'ACELERACION_ART':'float64', 'ACELERACION_SUBCLASE':'float64', 'ACELERACION_CLASE':'float64'})
    
    #Armamos df principal
    cab = dim.merge(ac[['LOCAL', 'ITEM', 'ACELERACION_ART']],
                    how='left').merge(ac[['LOCAL', 'SUBCLASE', 'ACELERACION_SUBCLASE']],
                                      how='left').merge(ac[['LOCAL', 'CLASE', 'ACELERACION_CLASE']],
                                                        how='left').drop_duplicates().reset_index(drop=True)
    #Definimos aceleración
    cab['ACELERACION'] = cab['ACELERACION_ART']
    cab.loc[cab[cab['ACELERACION'].isna()].index,
            'ACELERACION'] = cab.loc[cab[cab['ACELERACION'].isna()].index, 'ACELERACION_SUBCLASE']
    cab.loc[cab[cab['ACELERACION'].isna()].index,
            'ACELERACION'] = cab.loc[cab[cab['ACELERACION'].isna()].index, 'ACELERACION_CLASE']
    
    #Donde no tengamos dato de aceleración o donde esta sea menor a 1 asumimos que no se acelera
    cab.fillna({'ACELERACION':1}, inplace=True)
    cab.loc[cab[cab['ACELERACION']<1].index, 'ACELERACION'] = 1

    #Definimos unidades diarias y DOH
    cab['UNIDADES_DIARIAS_POR_ACELERACION'] = cab['AVG_BASAL_180']*cab['ACELERACION']
    cab['DOH_ESTANTE_MIN'] = round(cab['CANT_MIN_X_ESTANTE']/cab['UNIDADES_DIARIAS_POR_ACELERACION'])
    cab['DOH_ESTANTE_MAX'] = round(cab['CANT_MAX_X_ESTANTE']/cab['UNIDADES_DIARIAS_POR_ACELERACION'])

    #Limpiamos un poco el df de cabeceras
    cab.drop(index=cab[~cab['ITEM'].isin(punt['ITEM'].unique())].index, inplace=True)

    #Tomamos columnas que interesan
    cab = cab[['LOCAL', 'NOMBRE_TIENDA', 'GRUPO', 'CLASE', 'SUBCLASE', 'ITEM', 'ARTC_ARTC_DESC', 'AVG_BASAL_180',
               'ACELERACION', 'UNIDADES_DIARIAS_POR_ACELERACION', 'PROFUNDIDAD', 'FRENTE', 'ALTURA',
               'CANT_MAX_X_ESTANTE', 'CANT_MIN_X_ESTANTE', 'DOH_ESTANTE_MIN', 'DOH_ESTANTE_MAX']]

    #Algoritmo que define la participación por puntera
    df_final = pd.DataFrame()
    for l in punt['LOCAL'].unique():
        df = punt[(punt['LOCAL']==l)].drop_duplicates()
        for p in df['PUNTERA'].unique():
            try:
                df = punt[(punt['LOCAL']==l) &
                          (punt['PUNTERA']==p)].drop(columns='DESCRIPCION').merge(cab).drop_duplicates()
                df['PARTICIPACION'] = np.NaN
                if df[df['DOH_ESTANTE_MAX'] <= 31].shape[0] >= 5:
                    #print('ESTANTES INSUFICIENTES')
                    if df.shape[0] >= 7:
                        it_may_vta = df.sort_values('DOH_ESTANTE_MAX').head(3)['ITEM'].values
                        it_h_vta = df.sort_values('DOH_ESTANTE_MAX').head()['ITEM'].values
                        df.loc[df[df['ITEM'].isin(it_may_vta)].index, 'PARTICIPACION'] = 1
                        df.loc[df[(~df['ITEM'].isin(it_may_vta)) &
                                    (df['ITEM'].isin(it_h_vta))].index, 'PARTICIPACION'] = 0.5
                        df.loc[df[~df['ITEM'].isin(it_h_vta)].index,
                                'PARTICIPACION'] = 1/df[~df['ITEM'].isin(it_h_vta)].shape[0]
                    elif df.shape[0] == 6:
                        it_may_vta = df.sort_values('DOH_ESTANTE_MAX').head(4)['ITEM'].values
                        df.loc[df[df['ITEM'].isin(it_may_vta)].index, 'PARTICIPACION'] = 1
                        df.loc[df[(~df['ITEM'].isin(it_may_vta))].index, 'PARTICIPACION'] = 0.5
                    else:
                        df.loc[df.index, 'PARTICIPACION'] = 1
                elif df.shape[0] == 1:
                    df['PARTICIPACION'] = 5
                elif df.shape[0] <= 3:
                    t = df['DOH_ESTANTE_MAX'].sum()
                    df['PARTICIPACION'] = t/df['DOH_ESTANTE_MAX']
                    t = df['PARTICIPACION'].sum()
                    df['PARTICIPACION'] = 5*df['PARTICIPACION']/t
                    df['PARTICIPACION'] = df['PARTICIPACION'].apply(red3)
                elif df.shape[0] <= 7:
                    t = df['DOH_ESTANTE_MAX'].sum()
                    df['PARTICIPACION'] = t/df['DOH_ESTANTE_MAX']
                    t = df['PARTICIPACION'].sum()
                    df['PARTICIPACION'] = 5*df['PARTICIPACION']/t
                    df['PARTICIPACION'] = df['PARTICIPACION'].apply(red7)
                else:
                    t = df['DOH_ESTANTE_MAX'].sum()
                    df['PARTICIPACION'] = t/df['DOH_ESTANTE_MAX']
                    t = df['PARTICIPACION'].sum()
                    df['PARTICIPACION'] = 5*df['PARTICIPACION']/t
                    df['PARTICIPACION'] = df['PARTICIPACION'].apply(red)
                df = cerrar(df=df)
                df_final = pd.concat([df_final, df], ignore_index=True)
            except:
                pass
    
    #Vemos los items que no teniamos datos de aceleración/dimensiones
    df_final['DURACION'] = (pd.to_datetime(df_final['FECHA_FIN']) -
                            pd.to_datetime(df_final['FECHA_INICIO'])).mean().days + 1
    #Agregamos los faltantes
    df_final['UNIDADES_CARGA_POR_VENTA'] = df_final['DURACION']*df_final['UNIDADES_DIARIAS_POR_ACELERACION']
    df_final['UNIDADES_CARGA_MAX_POR_PARTICIPACION'] = df_final['PARTICIPACION']*df_final['CANT_MAX_X_ESTANTE']
    df_final['UNIDADES_CARGA_MIN_POR_PARTICIPACION'] = df_final['PARTICIPACION']*df_final['CANT_MIN_X_ESTANTE']

    df_final = df_final[['FECHA_INICIO', 'FECHA_FIN', 'SECCION', 'LOCAL', 'NOMBRE_TIENDA', 'PUNTERA',
                         'GRUPO', 'CLASE', 'SUBCLASE', 'ESTADISTICO', 'ITEM', 'ARTC_ARTC_DESC',
                         'AVG_BASAL_180', 'ACELERACION', 'UNIDADES_DIARIAS_POR_ACELERACION',
                         'PROFUNDIDAD', 'FRENTE', 'ALTURA', 'CANT_MAX_X_ESTANTE', 'CANT_MIN_X_ESTANTE',
                         'DOH_ESTANTE_MIN', 'DOH_ESTANTE_MAX', 'PARTICIPACION', 'DURACION', 'UNIDADES_CARGA_POR_VENTA',
                         'UNIDADES_CARGA_MAX_POR_PARTICIPACION', 'UNIDADES_CARGA_MIN_POR_PARTICIPACION']]
    return df_final

In [3]:
scopes = ['https://www.googleapis.com/auth/spreadsheets',
          'https://www.googleapis.com/auth/drive']

# keyboard.press_and_release('ctrl+w')        #Close the window

credentials = Credentials.from_service_account_file('api_credentials_2.json', scopes=scopes)

gc = gspread.authorize(credentials)
gauth = GoogleAuth()
drive = GoogleDrive(gauth)

In [4]:
def renombrar_columnas(col_name):
    if re.search(r'EXHIBI', col_name, re.IGNORECASE):
        return f'PUNTERA'
    elif re.search(r'^ESTAD', col_name, re.IGNORECASE):
        return f'ESTADISTICO'
    elif re.search(r'^TEM', col_name, re.IGNORECASE):
        return f'ITEM'
    elif re.search(r'^Descripc', col_name, re.IGNORECASE):
        return f'DESCRIPCION'
    else:
        return col_name

In [5]:
url = 'https://docs.google.com/spreadsheets/d/1yME79mb27tG3FNLton-2pgEMH7oRjqXZMDWtwoQP-qQ/edit?pli=1&gid=350335113#gid=350335113'
sheet = url.split('/')[-2]
gs = gc.open_by_key(sheet)

In [7]:
meses = {"Enero": 1, "Febrero": 2, "Marzo": 3, "Abril": 4, "Mayo": 5, "Junio": 6, "Julio": 7,
            "Agosto": 8, "Septiembre": 9, "Octubre": 10, "Noviembre": 11, "Diciembre": 12}
mes = 'Agosto'
fecha = date.today().replace(month=meses[mes])
fecha

datetime.date(2026, 8, 13)

In [8]:
if fecha <= date.today():
    fecha = fecha.replace(year=date.today().year + 1)

In [9]:
fecha_inicio = fecha.replace(day=1).strftime('%Y-%m-%d')
fecha_fin = fecha.replace(day=calendar.monthrange(date.today().replace(month=fecha.month).year,
                                                date.today().replace(month=fecha.month).month)[1]).strftime('%Y-%m-%d')
print('Fecha inicio: ' + fecha_inicio)
print('Fecha fin: ' + fecha_fin)

Fecha inicio: 2026-08-01
Fecha fin: 2026-08-31

In [10]:
df_total = pd.DataFrame()

# Obtener todas las hojas en el Google Sheet
hojas = gs.worksheets()

# Iterar sobre cada hoja
for hoja in hojas:
    # Convertir la hoja actual a DataFrame
    worksheetL = gs.worksheet(hoja.title)
    juli0 = get_as_dataframe(worksheetL, header=None)
    
    # Encontrar la fila que contiene la palabra "EXHIBICION" en la primera columna
    col_0 = juli0.iloc[:, 0].astype(str)  # Ensure column 0 is all strings

    mask = col_0.str.contains("EXHIBICIÓN", na=False)

    condicion = juli0[mask].index[0] if mask.any() else None

    if condicion is not None:
        # Filtrar las filas a partir de la condición
        df = juli0.loc[condicion:, 0:5]
        df.columns = df.iloc[0]  # Definir la primera fila como encabezado
        df = df[1:].reset_index(drop=True)  # Reiniciar el índice
        
        # Renombrar columnas del DataFrame
        df.rename(columns=renombrar_columnas, inplace=True)

        df = df.dropna(subset=['PUNTERA'])
        
        # Limpiar columnas antes de convertir a enteros
        for col in ['ESTADISTICO', 'ITEM', 'LOCAL']:
            df[col] = df[col].astype(str)
            df[col] = df[col].str.replace('.', '', regex=False).fillna('0')
            df[col] = df[col].str.replace('nan', '0', regex=False).fillna('0')
            #df[col] = df[col].astype(int)
        df['SECCION'] = hoja.title

        # Concatenar el DataFrame actual con el total
        df_total = pd.concat([df_total, df], ignore_index=True).drop_duplicates()

#Definimos las columnas que nos interesan
df_total = df_total[['PUNTERA', 'ESTADISTICO', 'ITEM', 'DESCRIPCION', 'LOCAL', 'SECCION']]
df_total

,PUNTERA,ESTADISTICO,ITEM,DESCRIPCION,LOCAL,SECCION
0,CABECERA VAN DAM,261509000,1000055471,BOMBONERA LECHE BON O BON 270 G,101,Almacen
1,CABECERA VAN DAM,261509000,1000055471,BOMBONERA LECHE BON O BON 270 G,111,Almacen
2,CABECERA VAN DAM,261509000,1000055471,BOMBONERA LECHE BON O BON 270 G,115,Almacen
3,CABECERA VAN DAM,261509000,1000055471,BOMBONERA LECHE BON O BON 270 G,125,Almacen
4,CABECERA VAN DAM,261509000,1000055471,BOMBONERA LECHE BON O BON 270 G,126,Almacen
...,...,...,...,...,...,...
13291,CABECERAS,330805000,1000469754,SOFRITO FRUTOS DEL MAIPO 150 G,101,Congelados
13292,CABECERAS,330177000,1000059137,HAMBURGUESA CLASICA LA DOLFINA 150 GRS 3.00 U,101,Congelados
13293,CABECERAS,331636000,1000059548,HAMBURGUESA DE POLLO REB SADINESA 1.00 U,101,Congelados
13294,EQUIPO SADIA,331636000,1000059548,HAMBURGUESA DE POLLO REBOZADA SADINESA 1 UD,124,Congelados
13295,EQUIPO SADIA,331636000,1000059548,HAMBURGUESA DE POLLO REBOZADA SADINESA 1 UD,124,Congelados

In [11]:
# Mostrar las primeras filas del DataFrame total
print('Cantidad de registros: ' + str(df_total.shape[0]))
df_total['FECHA_INICIO'] = fecha_inicio
df_total['FECHA_FIN'] = fecha_fin
df_total

Cantidad de registros: 13296

,PUNTERA,ESTADISTICO,ITEM,DESCRIPCION,LOCAL,SECCION,FECHA_INICIO,FECHA_FIN
0,CABECERA VAN DAM,261509000,1000055471,BOMBONERA LECHE BON O BON 270 G,101,Almacen,2026-08-01,2026-08-31
1,CABECERA VAN DAM,261509000,1000055471,BOMBONERA LECHE BON O BON 270 G,111,Almacen,2026-08-01,2026-08-31
2,CABECERA VAN DAM,261509000,1000055471,BOMBONERA LECHE BON O BON 270 G,115,Almacen,2026-08-01,2026-08-31
3,CABECERA VAN DAM,261509000,1000055471,BOMBONERA LECHE BON O BON 270 G,125,Almacen,2026-08-01,2026-08-31
4,CABECERA VAN DAM,261509000,1000055471,BOMBONERA LECHE BON O BON 270 G,126,Almacen,2026-08-01,2026-08-31
...,...,...,...,...,...,...,...,...
13291,CABECERAS,330805000,1000469754,SOFRITO FRUTOS DEL MAIPO 150 G,101,Congelados,2026-08-01,2026-08-31
13292,CABECERAS,330177000,1000059137,HAMBURGUESA CLASICA LA DOLFINA 150 GRS 3.00 U,101,Congelados,2026-08-01,2026-08-31
13293,CABECERAS,331636000,1000059548,HAMBURGUESA DE POLLO REB SADINESA 1.00 U,101,Congelados,2026-08-01,2026-08-31
13294,EQUIPO SADIA,331636000,1000059548,HAMBURGUESA DE POLLO REBOZADA SADINESA 1 UD,124,Congelados,2026-08-01,2026-08-31
13295,EQUIPO SADIA,331636000,1000059548,HAMBURGUESA DE POLLO REBOZADA SADINESA 1 UD,124,Congelados,2026-08-01,2026-08-31

In [12]:
print('Articulos repetidos en puntera:')
rep = df_total[['LOCAL', 'PUNTERA', 'ITEM']]
df_total.loc[rep[rep.duplicated(keep=False)].index].sort_values(['LOCAL', 'PUNTERA', 'ITEM'])

Articulos repetidos en puntera:

,PUNTERA,ESTADISTICO,ITEM,DESCRIPCION,LOCAL,SECCION,FECHA_INICIO,FECHA_FIN
13294,EQUIPO SADIA,331636000,1000059548,HAMBURGUESA DE POLLO REBOZADA SADINESA 1 UD,124,Congelados,2026-08-01,2026-08-31
13295,EQUIPO SADIA,331636000,1000059548,HAMBURGUESA DE POLLO REBOZADA SADINESA 1 UD,124,Congelados,2026-08-01,2026-08-31

In [14]:
print('Articulos en varias punteras de un solo local:')
rep = df_total[['LOCAL', 'ITEM']]
df_total.loc[rep[rep.duplicated(keep=False)].index].sort_values(['LOCAL', 'ITEM'])

Articulos en varias punteras de un solo local:

,PUNTERA,ESTADISTICO,ITEM,DESCRIPCION,LOCAL,SECCION,FECHA_INICIO,FECHA_FIN
5790,CABECERA COLGATE ANUAL,160216000,1000037642,CREMA DENTAL COLGATE TOTAL 12 WHITENING 90 G,101,PyL,2026-08-01,2026-08-31
6042,LATERAL CHICO,160216000,1000037642,CREMA DENTAL COLGATE TOTAL 12 WHITENING 90 G,101,PyL,2026-08-01,2026-08-31
5791,CABECERA COLGATE ANUAL,160288000,1000037689,CREMA DENTAL COLGATE CALCIO 90 G,101,PyL,2026-08-01,2026-08-31
6043,LATERAL CHICO,160288000,1000037689,CREMA DENTAL COLGATE CALCIO 90 G,101,PyL,2026-08-01,2026-08-31
6630,CABECERA ANUAL FORTYLEX,162433000,1000039069,TOALLA HIGIENICA SIEMPRE LIBRE ESPECIAL CON AL...,101,PyL,2026-08-01,2026-08-31
...,...,...,...,...,...,...,...,...
6129,EXHIBIDOR COLGATE NUEVO,167101000,1000592682,CREMA DENTAL COLGATE LUMINOUS WHITE COLOR CORR...,328,PyL,2026-08-01,2026-08-31
10773,SALUS EXHIBIDOR,240513000,1000150629,SALUS FRUTTE NARANJA-DURAZNO CERO 1.5 LT,334,Bebidas,2026-08-01,2026-08-31
11162,CABECERA SALUS NEGO,240513000,1000150629,SALUS FRUTTE NARANJA-DURAZNO CERO 1.5 LT,334,Bebidas,2026-08-01,2026-08-31
10771,SALUS EXHIBIDOR,241641000,1000568930,FRUTTE SIN AZUCAR MANGO NARANJA 1.5 LT,334,Bebidas,2026-08-01,2026-08-31
11163,CABECERA SALUS NEGO,241641000,1000568930,FRUTTE SIN AZUCAR MANGO NARANJA 1.5 LT,334,Bebidas,2026-08-01,2026-08-31

In [17]:
credentials_snowflake = get_credentials("snow")

In [18]:
user, cursor, snow = snowflake_login(
                                    user = credentials_snowflake['USER'],
                                    password = credentials_snowflake['PASS'],
                                    account = credentials_snowflake['ACCOUNT']
                                    )

Intento 1
Correct Password - connected to SNOWFLAKE

In [19]:
fecha_inicio = df_total['FECHA_INICIO'].values[0]
cursor.execute("SELECT * FROM SANDBOX_PLUS.DWH.INPUT_PUNTERAS WHERE FECHA_INICIO = '" + fecha_inicio + "';")
df_old = cursor.fetch_pandas_all()
df_old

Empty DataFrame
Columns: [PUNTERA, ESTADISTICO, ITEM, DESCRIPCION, LOCAL, FECHA_INICIO, FECHA_FIN, SECCION]
Index: []

In [22]:
df_total['ITEM'].unique()

array(['1000055471', '1000055202', '1000302904', '1000055475',
       '1000052874', '1000052863', '1000052739', '1000056037',
       '1000056040', '1000056038', '1000056039', '1000054784',
       '1000054905', '1000345459', '1000055345', '1000436504',
       '1000599319', '1000599321', '1000052960', '1000053769',
       '1000102658', '1000053752', '1000053754', '1000053763',
       '1000052980', '1000454086', '1000053371', '1000053370',
       '1000052527', '1000435994', '1000581269', '1000581284',
       '1000581270', '1000055028', '1000055034', '1000055635',
       '1000055633', '1000055843', '1000055634', '1000054975',
       '1000055865', '1000055807', '1000055808', '1000055868',
       '1000055723', '1000055016', '1000300270', '1000055744',
       '1000436723', '1000052323', '1000050441', '1000598821',
       '1000052921', '1000368339', '1000114827', '1000056104',
       '1000056111', '1000436794', '1000436795', '1000447139',
       '1000056217', '1000460962', '1000056218', '1000363277',
       '1000056141', '1000056143', '1000168829', '1000431742',
       '1000420760', '1000420759', '1000420823', '1000052664',
       '1000052663', '1000052665', '1000052834', '1000434883',
       '1000053063', '1000406794', '1000053064', '1000052683',
       '1000052550', '1000052659', '1000053668', '1000053646',
       '1000052713', '1000554591', '1000053466', '1000050471',
       '1000453983', '1000453984', '1000456828', '1000052614',
       '1000050461', '1000050501', '1000461444', '1000461443',
       '1000461537', '1000461578', '1000461608', '1000578438',
       '1000580549', '1000050993', '1000050995', '1000051006',
       '1000051007', '1000050992', '1000051004', '1000051070',
       '1000051080', '1000056265', '1000041930', '1000041929',
       '1000041932', '1000041943', '1000582758', '1000027336',
       '1000434613', '1000601417', '1000462632', '1000462641',
       '1000149604', '1000582261', '1000026344', '1000501028',
       '1000292633', '1000292634', '1000152586', '1000161944',
       '1000026465', '1000026466', '1000026467', '1000026468',
       '1000026469', '1000367318', '1000143890', '1000523721',
       '1000026452', '1000026453', '1000026457', '1000026459',
       '1000026693', '1000026575', '1000026588', '1000501639',
       '1000026607', '1000568789', '1000025974', '1000568700',
       '1000026779', '1000026361', '1000025795', '1000027226',
       '1000456728', '1000103830', '1000523578', '1000040508',
       '1000417419', '1000037695', '1000580511', '1000568997',
       '1000278008', '1000434405', '1000037642', '1000037689',
       '1000434406', '1000193163', '1000347408', '1000580551',
       '1000592682', '1000039795', '1000599301', '1000599324',
       '1000599325', '1000599423', '1000599429', '1000599437',
       '1000039069', '1000039095', '1000040397', '1000040400',
       '1000040445', '1000451744', '1000041824', '1000041838',
       '1000041839', '1000041840', '1000461757', '1000039625',
       '1000040431', '1000037906', '1000037915', '1000037919',
       '1000037932', '1000461472', '1000528126', '1000528147',
       '1000408528', '1000038888', '1000038957', '1000040717',
       '1000040780', '1000040970', '1000041183', '1000303876',
       '1000408526', '1000408527', '1000408529', '1000408530',
       '1000501647', '1000501650', '1000501651', '1000517219',
       '1000518621', '1000541080', '1000570221', '1000570222',
       '1000570226', '1000582185', '1000582186', '1000582187',
       '1000592431', '1000591962', '1000522072', '1000039053',
       '1000434343', '1000101039', '1000327356', '1000327357',
       '1000327358', '1000327359', '1000218425', '1000370512',
       '1000218424', '1000218422', '1000218421', '1000370511',
       '1000040901', '1000040705', '1000040804', '1000040615',
       '1000040601', '1000040623', '1000172660', '1000580567',
       '1000580568', '1000580660', '1000580661', '1000580569',
       'SHAMPOO DOVE UV REPAIR 200 ML',
       'SHAMPOO DOVE OLEO NUTRICION 200 ML',
       'SHAMPOO DOVE RECONSTRUCCION COMPLETA 20000 ML',
       'SHAMPOO DOVE REGENERACION EXTREMA 200 ML',
       'SHAMPOO DOVE HIDRATACION INTENSA 200 ML',
       'SHAMPOO DOVE BOND INTENSE REPAIR 200 ML',
       'DOVE SHAMPOO UV REPAIR 400 ML',
       'SHAMPOO DOVE HIDRATACION INTENSA 400 ML',
       'SHAMPOO DOVE RECONSTRUCCION COMPLETA 400 ML',
       'SHAMPOO DOVE OLEO NUTRICION 400 ML',
       'SHAMPOO DOVE REGENERACION EXTREMA 400 CC',
       'SHAMPOO DOVE BOND INTENSE REPAIR 400 ML',
       'ACONDICIONADOR DOVE OLEO NUTRICION 200 ML',
       'ACONDICIONADOR DOVE RECONSTRUCCION COMPLETA 200 ML',
       'ACONDICIONADOR DOVE HIDRATACION INTENSA 200 ML',
       'ACONDICIONADOR DOVE REGENERACION EXTREMA 200 CC',
       'ACONDICIONADOR DOVE UV REPAIR 250 ML',
       'ACONDICIONADOR DOVE BOND INTENSE REPAIR 250 ML',
       'ACONDICIONADOR DOVE OLEO NUTRICION 400 ML',
       'ACONDICIONADOR DOVE HIDRATACION INTENSA 400 ML',
       'ACONDICIONADOR DOVE REGENERACION EXTREMA 400 ML',
       'ACONDICIONADOR DOVE RECONSTRUCCION COMPLETA 400 ML',
       'MASCARA DOVE RECONSTRUCCION 270 GR',
       'MASCARA DOVE HIDRATACION 270 GR',
       'MASCARILLA DOVE UV REPAIR 250 GR',
       'MASCARA DOVE BOND INTENSE REPAIR 250 GR',
       'DOVE OLEO BOND INTENSE REPARACION 110 ML',
       'SERUM PARA CABELLO HIDRATACION DOVE 110 ML',
       'DOVE OLEO UV REPAIR 110 ML', '1000456824', '1000217118',
       '1000049899', '1000049901', '1000461360', '1000417644',
       '1000049050', '1000049049', '1000049475', '1000211324',
       '1000048525', '1000048524', '1000048528', '1000048526',
       '1000155840', '1000048495', '1000162728', '1000049412',
       '1000111218', '1000111347', '1000416833', '1000435383',
       '1000599733', '1000111220', '1000596980', '1000598224',
       '1000048394', '1000049906', '1000049884', '1000049915',
       '1000049917', '1000049902', '1000048961', '1000048962',
       '1000601812', '1000049615', '1000049590', '1000049601',
       '1000150628', '1000049604', '1000049606', '1000347005',
       '1000049624', '1000150632', '1000413344', '1000150603',
       '1000500661', '1000150629', '1000568930', '1000049603',
       '1000150633', '1000049605', '1000049584', '1000417052',
       '1000568932', '1000369408', '1000369407', '1000049265',
       '1000049196', '1000412426', '1000049291', '1000049864',
       '1000469146', '1000461442', '1000461441', '1000049376',
       '1000049377', '1000049378', '1000049380', '1000049383',
       '1000049351', '1000049353', '1000049354', '1000049355',
       '1000049384', '1000048326', '1000217968', '1000048181',
       '1000048180', '1000456650', '1000599273', '1000048929',
       '1000599294', '1000048318', '1000048319', '1000048320',
       '1000048321', '1000048322', '1000048323', '1000456715',
       '1000456724', '1000456731', '1000456795', '1000458025',
       '1000048868', '1000048867', '1000048871', '1000048882',
       '1000048873', '1000048874', '1000048866', '1000048872',
       '1000048862', '1000047944', '1000047948', '1000524461',
       '1000524462', '1000524722', '1000047927', '1000047926',
       '1000047969', '1000047972', '1000047970', '1000047952',
       '1000047966', '1000047961', '1000047968', '1000047967',
       '1000047950', '1000048066', '1000048067', '1000431746',
       '1000431758', '1000524663', '1000370535', '1000370480',
       '1000591031', '1000462028', '1000385297', '1000385299',
       '1000495248', '1000495671', '1000495247', '1000469754',
       '1000059137', '1000059548'], dtype=object)

In [21]:
success = carga_snow_generic(df_total.astype({'ESTADISTICO':'int64', 'ITEM':'int64', 'LOCAL':'int64'}),
                             ctx=snow, database='SANDBOX_PLUS', table='INPUT_PUNTERAS', schema='DWH')

ValueError: invalid literal for int() with base 10: 'SHAMPOO DOVE UV REPAIR 200 ML': Error while type casting for column 'ITEM'